[package]
name = "apars-proc-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
parse-more = "0.1.0"

[lib]
proc-macro = true
