[package]
name = "functional-type-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["visit", "visit-mut"] }
quote = "1.0"
parse-more = "0.2.2"
proc-macro2 = "1.0"

[lib]
proc-macro = true
